### ISSUE TITLE
results are too bad 

### ISSUE THREAD

**Issue by sudip550** [felicia-puzone/virtual-try-on-app#2]
results are too bad. its not working.

**Comment by sudip550** [comment]
why you are not responding??

**Comment by MRTCc** [comment]
Keep calm, dude. This is only a prototype for a Computer Vision Course of a Master Degree in Engineering Artificial Intelligence. We do not expect that it works perfectly fine on every possible machine and system: it is not our goal to deploy it in some e-commerce, but we only want to show our professors we mastered the course syllabus.

**Comment by sudip550** [comment]
> Keep calm, dude. This is only a prototype for a Computer Vision Course of a Master Degree in Engineering Artificial Intelligence. We do not expect that it works perfectly fine on every possible machine and system: it is not our goal to deploy it in some e-commerce, but we only want to show our professors we mastered the course syllabus.

Means you will not post complete project on github??

**Comment by MRTCc** [comment]
We have posted all the code, but we are not allowed to post the DressoCode dataset.

**Comment by sudip550** [comment]
> We have posted all the code, but we are not allowed to post the DressoCode dataset.

I want to use your notebook for custom clothes......can you please help me in this..

**Comment by sudip550** [comment]
please provide this two files = 1) TOM_step_250000_dresses.pth 2) gmm step 200000 dresses.pth

please sir.....

**Comment by sudip550** [comment]
> please provide this two files = 1) TOM_step_250000_dresses.pth 2) gmm step 200000 dresses.pth
> 
> please sir.....

please...... provide this files

**Comment by sudip550** [comment]
> We have posted all the code, but we are not allowed to post the DressoCode dataset.

Please....... provide thus model files...
